// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
	"strings"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the AddAttachment tool
const AddAttachmentInputSchema = "{\n  \"properties\": {\n    \"file\": {\n      \"description\": \"File to upload (URI reference — the file will be downloaded and uploaded to the upstream service)\",\n      \"format\": \"uri\",\n      \"type\": \"string\"\n    },\n    \"issueIdOrKey\": {\n      \"description\": \"Issue id or key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"file\",\n    \"issueIdOrKey\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the AddAttachment tool (Status: 200, Content-Type: application/json)
const AddAttachmentResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a JSON representation of the attachments added.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **author** (Type: object):\n    - **active** (Type: boolean):\n        - Example: 'true'\n    - **avatarUrls** (Type: object):\n        - Example: '\"http://www.example.com/jira/secure/projectavatar?size=xsmall\\u0026pid=10000\"'\n      - **Additional Properties**:\n        - **property value** (Type: string):\n            - Example: 'http://www.example.com/jira/secure/projectavatar?size=xsmall&pid=10000'\n    - **displayName** (Type: string):\n        - Example: 'Fred F. User'\n    - **emailAddress** (Type: string):\n        - Example: 'fred@example.com'\n    - **key** (Type: string):\n        - Example: 'fred'\n    - **name** (Type: string):\n        - Example: 'Fred'\n    - **self** (Type: string):\n        - Example: 'http://www.example.com/jira/rest/api/2/user?username=fred'\n    - **timeZone** (Type: string):\n        - Example: 'Australia/Sydney'\n  - **content** (Type: string):\n  - **created** (Type: string, date-time):\n  - **filename** (Type: string):\n  - **id** (Type: string):\n  - **mimeType** (Type: string):\n  - **self** (Type: string):\n  - **size** (Type: integer, int64):\n  - **thumbnail** (Type: string):\n"

// NewAddAttachmentMCPTool creates the MCP Tool instance for AddAttachment
func NewAddAttachmentMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"AddAttachment",
		"Add one or more attachments to an issue - Add one or more attachments to an issue.\nThis resource expects a multipart post. The media-type multipart/form-data is defined in RFC 1867. Most client libraries have classes that make dealing with multipart posts simple. For instance, in Java the Apache HTTP Components library provides a MultiPartEntity that makes it simple to submit a multipart POST.\nIn order to protect against XSRF attacks, because this method accepts multipart/form-data, it has XSRF protection\non it. This means you must submit a header of X-Atlassian-Token: no-check with the request, otherwise it will be blocked.\nThe name of the multipart/form-data parameter that contains attachments must be file.\nA simple example to upload a file called \"myfile.txt\" to issue TEST-123:\ncurl -D- -u admin:admin -X POST -H \"X-Atlassian-Token: no-check\" -F \"file=@myfile.txt\" http://myhost/rest/api/2/issue/TEST-123/attachments",
		[]byte(AddAttachmentInputSchema),
	)
}

// AddAttachmentHandler is the handler function for the AddAttachment tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func AddAttachmentHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	// FileRef: collect file URI values. Optional files that are not provided
	// are omitted from the multipart body. Non-URI values remain available for
	// anyOf binary|string multipart schemas and are forwarded as text fields.
	fileRefs := map[string]string{
		"file": "",
	}
	if uri, ok := args["file"].(string); ok {
		// Strip @ prefix (AI agent convention: @file://, @https://, @http://).
		// The client MUST provide an explicit scheme (file://, https://, http://).
		// Bare paths are treated as literal values, NOT auto-prefixed to file://,
		// because a bare path may be a legitimate non-file string argument.
		uri = strings.TrimPrefix(uri, "@")
		fileRefs["file"] = uri
	}
	return mcputils.ForwardMultipartRequest(ctx, upstream, "POST", "/rest/api/2/issue/{issueIdOrKey}/attachments", args, fileRefs, []string{"issueIdOrKey"}, []string{}, map[string]string{}, "AddAttachment")
}
