// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/mark3labs/mcp-go/mcp"
	mcputils "jira-mcp/pkg/helpers"
)

func TestNewDeleteProperty1_a6fb2a03MCPTool(t *testing.T) {
	tool := NewDeleteProperty1_a6fb2a03MCPTool()
	if tool.Name != "DeleteProperty1_a6fb2a03" {
		t.Errorf("unexpected tool name: got %q, want %q", tool.Name, "DeleteProperty1_a6fb2a03")
	}
	if tool.Description == "" {
		t.Error("tool description is empty")
	}
	if len(tool.RawInputSchema) == 0 {
		t.Error("tool input schema is empty")
	}
	var schema map[string]interface{}
	if err := json.Unmarshal(tool.RawInputSchema, &schema); err != nil {
		t.Errorf("tool input schema is not valid JSON: %v", err)
	}
	if schema["type"] != "object" {
		t.Errorf("schema type should be object, got %v", schema["type"])
	}
}

func TestDeleteProperty1_a6fb2a03Handler(t *testing.T) {
	handler := DeleteProperty1_a6fb2a03Handler
	if handler == nil {
		t.Fatal("handler is nil")
	}

	t.Run("upstream ok", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"ok":true}`))
		}))
		defer ts.Close()

		t.Setenv("MCP__UPSTREAM__DEFAULT__ENDPOINT", ts.URL)
		mcputils.LoadConfig("jira-mcp")

		req := mcp.CallToolRequest{
			Params: mcp.CallToolParams{
				Name:      "DeleteProperty1_a6fb2a03",
				Arguments: map[string]interface{}{},
			},
		}
		result, err := handler(context.Background(), req)
		if err != nil {
			t.Errorf("unexpected error: %v", err)
		}
		if result == nil {
			t.Fatal("result is nil")
		}
	})

	t.Run("nil args", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{}`))
		}))
		defer ts.Close()

		t.Setenv("MCP__UPSTREAM__DEFAULT__ENDPOINT", ts.URL)
		mcputils.LoadConfig("jira-mcp")

		req := mcp.CallToolRequest{
			Params: mcp.CallToolParams{
				Name: "DeleteProperty1_a6fb2a03",
			},
		}
		result, err := handler(context.Background(), req)
		if err != nil {
			t.Errorf("unexpected error with nil args: %v", err)
		}
		if result == nil {
			t.Fatal("result is nil")
		}
	})

	t.Run("upstream error 500", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusInternalServerError)
			w.Write([]byte(`{"error":"internal"}`))
		}))
		defer ts.Close()

		t.Setenv("MCP__UPSTREAM__DEFAULT__ENDPOINT", ts.URL)
		mcputils.LoadConfig("jira-mcp")

		req := mcp.CallToolRequest{
			Params: mcp.CallToolParams{
				Name:      "DeleteProperty1_a6fb2a03",
				Arguments: map[string]interface{}{},
			},
		}
		result, err := handler(context.Background(), req)
		if err != nil {
			t.Errorf("unexpected error: %v", err)
		}
		if result == nil {
			t.Fatal("result is nil")
		}
		if !result.IsError {
			t.Error("expected error result for 500 upstream, got success")
		}
	})
}
