// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the SetIssueNavigatorDefaultColumnsForm tool
const SetIssueNavigatorDefaultColumnsFormInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"columns\": {\n          \"items\": {\n            \"type\": \"string\"\n          },\n          \"type\": \"array\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewSetIssueNavigatorDefaultColumnsFormMCPTool creates the MCP Tool instance for SetIssueNavigatorDefaultColumnsForm
func NewSetIssueNavigatorDefaultColumnsFormMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"SetIssueNavigatorDefaultColumnsForm",
		"Set default system columns for issue navigator using form - Sets the default system columns for issue navigator. Admin permission will be required.",
		[]byte(SetIssueNavigatorDefaultColumnsFormInputSchema),
	)
}

// SetIssueNavigatorDefaultColumnsFormHandler is the handler function for the SetIssueNavigatorDefaultColumnsForm tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func SetIssueNavigatorDefaultColumnsFormHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/x-www-form-urlencoded"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/rest/api/2/settings/columns", args, []string{}, contentType, "SetIssueNavigatorDefaultColumnsForm")
}
